In [ ]:
import numpy as np

## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [16]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [18]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [20]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
arr = np.array([[1,2,3],[4,5,6]])

print("array:\n",arr)
print("shape:",arr.shape)
print("number of dimensions:",arr.ndim)
print("size:",arr.size)
print("data type:",arr.dtype)
print("item size (in bytes):",arr.itemsize)
print("total bytes:",arr.nbytes)


array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimensions: 2
size: 6
data type: int64
item size (in bytes): 8
total bytes: 48


In [31]:
data:int = 10
print(data)

10


In [33]:
### Numpy Vectorization Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### Element Wise Addition
print("Addition:",arr1 + arr2)

## Element Wise Substraction
print("Substraction:",arr2 - arr1)

Addition: [11 22 33 44 55]
Substraction: [ 9 18 27 36 45]


In [36]:
## Universal Function
arr = np.array([2,3,4,5,6])
# square root
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [38]:
## array slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
arr[0]

array([1, 2, 3, 4])

In [40]:
arr[0][0]

np.int64(1)

In [41]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [43]:
print(arr)
arr[0][0] = 100
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [50]:
data = np.array([1,2,3,4,5])

mean = np.mean(data)
print("Mean:",mean)

median = np.median(data)
print("Median:",median)

std_dev = np.std(data)
print("Standard Deviation:",std_dev)

normalized_data = (data - mean) / std_dev
print("Normalized Data:",normalized_data)

variance = np.var(data)
print("Variance:",variance)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Variance: 2.0


In [57]:
## Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data[data>5])
print(data[(data>3) & (data<8)])

[ 6  7  8  9 10]
[4 5 6 7]
